# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch # when this workflow executed
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  # This workflow contains a single job called "build"
  first-job: # non-reserved name
    runs-on: ubuntu-latest # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: # reserved name

      # Runs a single command using the runners shell
      - name: Print greeting
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Print Good Bye
        run: echo "Done - bye!"
